// 完整的78张塔罗牌数据
// 包含22张大阿卡纳和56张小阿卡纳

export interface TarotCardData {
  id: number;
  name: string;
  nameEn: string;
  nameJa: string;
  meaning: string;
  reversedMeaning: string;
  keywords: string[];
  imageUrl?: string;
  suit?: 'Wands' | 'Cups' | 'Swords' | 'Pentacles';
  number?: number;
}

// 大阿卡纳 (22张) - Major Arcana
export const majorArcana: TarotCardData[] = [
  {
    id: 0,
    name: '愚者',
    nameEn: 'The Fool',
    nameJa: '愚者',
    meaning: '新的开始、冒险、天真、自发性、自由精神',
    reversedMeaning: '鲁莽、冒险、愚蠢、不负责任',
    keywords: ['beginning', 'adventure', 'innocence', 'spontaneity', 'free spirit'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Fool_New_beginnings.png',
  },
  {
    id: 1,
    name: '魔术师',
    nameEn: 'The Magician',
    nameJa: '魔術師',
    meaning: '创造力、意志力、技能、专注、行动力',
    reversedMeaning: '欺骗、意志薄弱、能力滥用',
    keywords: ['creativity', 'willpower', 'skill', 'focus', 'manifestation'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Magician_Creativity.png',
  },
  {
    id: 2,
    name: '女祭司',
    nameEn: 'The High Priestess',
    nameJa: '女教皇',
    meaning: '直觉、神秘、潜意识、智慧、内在知识',
    reversedMeaning: '压抑情感、缺乏内在指引、秘密被揭露',
    keywords: ['intuition', 'mystery', 'subconscious', 'wisdom', 'inner knowledge'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_High_Priestess_Intuition.png',
  },
  {
    id: 3,
    name: '皇后',
    nameEn: 'The Empress',
    nameJa: '皇后',
    meaning: '丰饶、创造力、自然、养育、美丽',
    reversedMeaning: '创造力受阻、依赖他人、空虚',
    keywords: ['fertility', 'creativity', 'nature', 'nurturing', 'beauty'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Empress_Abundance.png',
  },
  {
    id: 4,
    name: '皇帝',
    nameEn: 'The Emperor',
    nameJa: '皇帝',
    meaning: '权威、结构、控制、领导力、稳定性',
    reversedMeaning: '控制欲过强、缺乏纪律、软弱',
    keywords: ['authority', 'structure', 'control', 'leadership', 'stability'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Emperor_Authority.png',
  },
  {
    id: 5,
    name: '教皇',
    nameEn: 'The Hierophant',
    nameJa: '教皇',
    meaning: '传统、精神指引、信仰、学习、从众',
    reversedMeaning: '反叛、新方法、限制自由、虚假信念',
    keywords: ['tradition', 'spiritual guidance', 'faith', 'learning', 'conformity'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Hierophant_Tradition.png',
  },
  {
    id: 6,
    name: '恋人',
    nameEn: 'The Lovers',
    nameJa: '恋人',
    meaning: '爱情、和谐、关系、价值观选择、结合',
    reversedMeaning: '不和谐、不平衡、错误选择、分离',
    keywords: ['love', 'harmony', 'relationships', 'choices', 'union'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Lovers_Love.png',
  },
  {
    id: 7,
    name: '战车',
    nameEn: 'The Chariot',
    nameJa: '戦車',
    meaning: '胜利、意志力、自律、决心、成功',
    reversedMeaning: '失去方向、攻击性、缺乏控制',
    keywords: ['victory', 'willpower', 'discipline', 'determination', 'success'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Chariot_Victory.png',
  },
  {
    id: 8,
    name: '力量',
    nameEn: 'Strength',
    nameJa: '力',
    meaning: '勇气、耐心、内在力量、慈悲、同情心',
    reversedMeaning: '软弱、自我怀疑、缺乏纪律',
    keywords: ['courage', 'patience', 'inner strength', 'compassion', 'control'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/Strength_Strength.png',
  },
  {
    id: 9,
    name: '隐士',
    nameEn: 'The Hermit',
    nameJa: '隠者',
    meaning: '内省、寻求真理、内在指引、孤独、智慧',
    reversedMeaning: '孤独、孤立、退缩、拒绝建议',
    keywords: ['introspection', 'seeking truth', 'inner guidance', 'solitude', 'wisdom'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Hermit_Introspection.png',
  },
  {
    id: 10,
    name: '命运之轮',
    nameEn: 'Wheel of Fortune',
    nameJa: '運命の輪',
    meaning: '改变、周期、命运、转折点、好运',
    reversedMeaning: '坏运气、抵抗变化、中断、破坏',
    keywords: ['change', 'cycles', 'fate', 'turning point', 'luck'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/Wheel_of_Fortune_Destiny.png',
  },
  {
    id: 11,
    name: '正义',
    nameEn: 'Justice',
    nameJa: '正義',
    meaning: '正义、公平、真理、因果、法律',
    reversedMeaning: '不公正、缺乏责任感、不诚实',
    keywords: ['justice', 'fairness', 'truth', 'causality', 'law'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/Justice_Justice.png',
  },
  {
    id: 12,
    name: '倒吊人',
    nameEn: 'The Hanged Man',
    nameJa: '吊るされた男',
    meaning: '牺牲、新视角、等待、放下、放手',
    reversedMeaning: '停滞、无谓牺牲、延迟',
    keywords: ['sacrifice', 'new perspective', 'waiting', 'letting go', 'surrender'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Hanged_Man_Sacrifice.png',
  },
  {
    id: 13,
    name: '死神',
    nameEn: 'Death',
    nameJa: '死神',
    meaning: '结束、转变、重生、新的开始、放手',
    reversedMeaning: '抗拒变化、无法放手、停滞',
    keywords: ['endings', 'transition', 'rebirth', 'new beginnings', 'letting go'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/Death_Change.png',
  },
  {
    id: 14,
    name: '节制',
    nameEn: 'Temperance',
    nameJa: '節制',
    meaning: '平衡、适度、耐心、目的、和谐',
    reversedMeaning: '不平衡、过度、缺乏耐心',
    keywords: ['balance', 'moderation', 'patience', 'purpose', 'harmony'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/Temperance_Balance.png',
  },
  {
    id: 15,
    name: '恶魔',
    nameEn: 'The Devil',
    nameJa: '悪魔',
    meaning: '束缚、物质主义、成瘾、无知、沉迷',
    reversedMeaning: '解放、打破束缚、重获力量',
    keywords: ['bondage', 'materialism', 'addiction', 'ignorance', 'attachment'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Devil_Temptation.png',
  },
  {
    id: 16,
    name: '高塔',
    nameEn: 'The Tower',
    nameJa: '塔',
    meaning: '突变、混乱、启示、觉醒、释放',
    reversedMeaning: '避免灾难、推迟改变、恐惧',
    keywords: ['sudden change', 'upheaval', 'revelation', 'awakening', 'release'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Tower_Sudden_change.png',
  },
  {
    id: 17,
    name: '星星',
    nameEn: 'The Star',
    nameJa: '星',
    meaning: '希望、灵感、平静、更新、精神力量',
    reversedMeaning: '绝望、缺乏信心、消极',
    keywords: ['hope', 'inspiration', 'peace', 'renewal', 'spiritual power'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Star_Hope.png',
  },
  {
    id: 18,
    name: '月亮',
    nameEn: 'The Moon',
    nameJa: '月',
    meaning: '幻觉、恐惧、焦虑、潜意识、直觉',
    reversedMeaning: '释放恐惧、压抑情绪、混乱',
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Moon_Illusion.png',
  },
  {
    id: 19,
    name: '太阳',
    nameEn: 'The Sun',
    nameJa: '太陽',
    meaning: '快乐、成功、活力、积极性、乐观',
    reversedMeaning: '暂时的挫折、缺乏成功、悲观',
    keywords: ['joy', 'success', 'vitality', 'positivity', 'optimism'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_Sun_Success.png',
  },
  {
    id: 20,
    name: '审判',
    nameEn: 'Judgement',
    nameJa: '審判',
    meaning: '审判、重生、内在召唤、宽恕、觉醒',
    reversedMeaning: '自我怀疑、拒绝召唤、忽视教训',
    keywords: ['judgment', 'rebirth', 'inner calling', 'absolution', 'awakening'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/Judgement_Rebirth.png',
  },
  {
    id: 21,
    name: '世界',
    nameEn: 'The World',
    nameJa: '世界',
    meaning: '完成、整合、成就、旅行、圆满',
    reversedMeaning: '未完成、缺乏封闭、拖延',
    keywords: ['completion', 'integration', 'accomplishment', 'travel', 'wholeness'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Major/The_World_Completion.png',
  },
];

// 小阿卡纳 - 权杖 (Wands) - 14张
export const wandsCards: TarotCardData[] = [
  {
    id: 22,
    name: '权杖王牌',
    nameEn: 'Ace of Wands',
    nameJa: 'ワンドのエース',
    meaning: '新的开始、灵感、行动、激情、创造力',
    reversedMeaning: '延迟、缺乏方向、缺乏激情',
    keywords: ['new beginnings', 'inspiration', 'action', 'passion', 'creativity'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ace_of_Wands_Creativity.png',
    suit: 'Wands',
    number: 1,
  },
  {
    id: 23,
    name: '权杖二',
    nameEn: 'Two of Wands',
    nameJa: 'ワンドの2',
    meaning: '规划、决策、发现、未来愿景',
    reversedMeaning: '害怕未知、拖延、缺乏计划',
    keywords: ['planning', 'decisions', 'discovery', 'future vision'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Two_of_Wands_Planning.png',
    suit: 'Wands',
    number: 2,
  },
  {
    id: 24,
    name: '权杖三',
    nameEn: 'Three of Wands',
    nameJa: 'ワンドの3',
    meaning: '扩张、远见、准备、进展',
    reversedMeaning: '挫折、缺乏进展、延迟',
    keywords: ['expansion', 'foresight', 'preparation', 'progress'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Three_of_Wands_Expansion.png',
    suit: 'Wands',
    number: 3,
  },
  {
    id: 25,
    name: '权杖四',
    nameEn: 'Four of Wands',
    nameJa: 'ワンドの4',
    meaning: '庆祝、和谐、家庭、稳定',
    reversedMeaning: '缺乏和谐、家庭问题、不稳定',
    keywords: ['celebration', 'harmony', 'home', 'stability'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Four_of_Wands_Stability.png',
    suit: 'Wands',
    number: 4,
  },
  {
    id: 26,
    name: '权杖五',
    nameEn: 'Five of Wands',
    nameJa: 'ワンドの5',
    meaning: '冲突、竞争、斗争、分歧',
    reversedMeaning: '避免冲突、团结、合作',
    keywords: ['conflict', 'competition', 'struggle', 'discord'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Five_of_Wands_Competition.png',
    suit: 'Wands',
    number: 5,
  },
  {
    id: 27,
    name: '权杖六',
    nameEn: 'Six of Wands',
    nameJa: 'ワンドの6',
    meaning: '胜利、成功、骄傲、认可',
    reversedMeaning: '失败、缺乏认可、自尊心过强',
    keywords: ['victory', 'success', 'pride', 'recognition'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Six_of_Wands_Victory.png',
    suit: 'Wands',
    number: 6,
  },
  {
    id: 28,
    name: '权杖七',
    nameEn: 'Seven of Wands',
    nameJa: 'ワンドの7',
    meaning: '挑战、防御、坚持、立场',
    reversedMeaning: '放弃、被压倒、缺乏防御',
    keywords: ['challenge', 'defensive', 'persistence', 'taking a stand'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Seven_of_Wands_Challenge.png',
    suit: 'Wands',
    number: 7,
  },
  {
    id: 29,
    name: '权杖八',
    nameEn: 'Eight of Wands',
    nameJa: 'ワンドの8',
    meaning: '速度、行动、快速移动、旅行',
    reversedMeaning: '延迟、挫折、缺乏进展',
    keywords: ['speed', 'action', 'rapid movement', 'travel'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Eight_of_Wands_Speed.png',
    suit: 'Wands',
    number: 8,
  },
  {
    id: 30,
    name: '权杖九',
    nameEn: 'Nine of Wands',
    nameJa: 'ワンドの9',
    meaning: '韧性、坚持、警惕、准备',
    reversedMeaning: '疲惫、缺乏准备、防御崩溃',
    keywords: ['resilience', 'persistence', 'vigilance', 'preparedness'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Nine_of_Wands_Persistence.png',
    suit: 'Wands',
    number: 9,
  },
  {
    id: 31,
    name: '权杖十',
    nameEn: 'Ten of Wands',
    nameJa: 'ワンドの10',
    meaning: '负担、压力、责任、过度劳累',
    reversedMeaning: '释放负担、委托、卸载',
    keywords: ['burden', 'stress', 'responsibility', 'overexertion'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ten_of_Wands_Burden.png',
    suit: 'Wands',
    number: 10,
  },
  {
    id: 32,
    name: '权杖侍从',
    nameEn: 'Page of Wands',
    nameJa: 'ワンドのペイジ',
    meaning: '新消息、灵感、探索、冒险精神',
    reversedMeaning: '缺乏灵感、坏消息、拖延',
    keywords: ['new messages', 'inspiration', 'exploration', 'adventure'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Page_of_Wands_Exploration.png',
    suit: 'Wands',
    number: 11,
  },
  {
    id: 33,
    name: '权杖骑士',
    nameEn: 'Knight of Wands',
    nameJa: 'ワンドのナイト',
    meaning: '行动、激情、冒险、快速移动',
    reversedMeaning: '缺乏方向、冲动、鲁莽',
    keywords: ['action', 'passion', 'adventure', 'rapid movement'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Knight_of_Wands_Adventure.png',
    suit: 'Wands',
    number: 12,
  },
  {
    id: 34,
    name: '权杖王后',
    nameEn: 'Queen of Wands',
    nameJa: 'ワンドのクイーン',
    meaning: '自信、独立、温暖、热情',
    reversedMeaning: '不自信、傲慢、自私、嫉妒',
    keywords: ['confidence', 'independence', 'warmth', 'enthusiasm'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Queen_of_Wands_Confidence.png',
    suit: 'Wands',
    number: 13,
  },
  {
    id: 35,
    name: '权杖国王',
    nameEn: 'King of Wands',
    nameJa: 'ワンドのキング',
    meaning: '领导力、愿景、企业家精神、决定',
    reversedMeaning: '专制、冲动、缺乏远见',
    keywords: ['leadership', 'vision', 'entrepreneurship', 'decisiveness'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/King_of_Wands_Leadership.png',
    suit: 'Wands',
    number: 14,
  },
];

// 小阿卡纳 - 圣杯 (Cups) - 14张
export const cupsCards: TarotCardData[] = [
  {
    id: 36,
    name: '圣杯王牌',
    nameEn: 'Ace of Cups',
    nameJa: 'カップのエース',
    meaning: '新的情感关系、爱情、精神觉醒、直觉',
    reversedMeaning: '情感压抑、情感空虚',
    keywords: ['new relationships', 'love', 'spiritual awakening', 'intuition'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ace_of_Cups_New_feelings.png',
    suit: 'Cups',
    number: 1,
  },
  {
    id: 37,
    name: '圣杯二',
    nameEn: 'Two of Cups',
    nameJa: 'カップの2',
    meaning: '伙伴关系、平等、和谐',
    reversedMeaning: '失衡、关系破裂、冲突',
    keywords: ['partnership', 'equality', 'harmony'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Two_of_Cups_Partnership.png',
    suit: 'Cups',
    number: 2,
  },
  {
    id: 38,
    name: '圣杯三',
    nameEn: 'Three of Cups',
    nameJa: 'カップの3',
    meaning: '庆祝、友谊、社交活动',
    reversedMeaning: '孤独、过度社交、庆祝不足',
    keywords: ['celebration', 'friendship', 'social events'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Three_of_Cups_Friendship.png',
    suit: 'Cups',
    number: 3,
  },
  {
    id: 39,
    name: '圣杯四',
    nameEn: 'Four of Cups',
    nameJa: 'カップの4',
    meaning: '冷漠、无聊、失望、内省',
    reversedMeaning: '新机会、觉醒、热情',
    keywords: ['apathy', 'boredom', 'disappointment', 'introspection'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Four_of_Cups_Apathy.png',
    suit: 'Cups',
    number: 4,
  },
  {
    id: 40,
    name: '圣杯五',
    nameEn: 'Five of Cups',
    nameJa: 'カップの5',
    meaning: '失去、悲伤、后悔、失望',
    reversedMeaning: '接受损失、继续前行、希望',
    keywords: ['loss', 'grief', 'regret', 'disappointment'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Five_of_Cups_Disappointment.png',
    suit: 'Cups',
    number: 5,
  },
  {
    id: 41,
    name: '圣杯六',
    nameEn: 'Six of Cups',
    nameJa: 'カップの6',
    meaning: '怀旧、童年记忆、快乐、纯真',
    reversedMeaning: '停留在过去、无法前行',
    keywords: ['nostalgia', 'childhood memories', 'joy', 'innocence'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Six_of_Cups_Nostalgia.png',
    suit: 'Cups',
    number: 6,
  },
  {
    id: 42,
    name: '圣杯七',
    nameEn: 'Seven of Cups',
    nameJa: 'カップの7',
    meaning: '选择、幻想、愿望、诱惑',
    reversedMeaning: '清晰、决策、现实',
    keywords: ['choices', 'fantasy', 'wishes', 'temptation'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Seven_of_Cups_Fantasy.png',
    suit: 'Cups',
    number: 7,
  },
  {
    id: 43,
    name: '圣杯八',
    nameEn: 'Eight of Cups',
    nameJa: 'カップの8',
    meaning: '离开、放弃、失望、寻求更多',
    reversedMeaning: '无法离开、被困住、继续探索',
    keywords: ['leaving', 'abandonment', 'disappointment', 'seeking more'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Eight_of_Cups_Abandonment.png',
    suit: 'Cups',
    number: 8,
  },
  {
    id: 44,
    name: '圣杯九',
    nameEn: 'Nine of Cups',
    nameJa: 'カップの9',
    meaning: '满足、愿望实现、幸福、满足感',
    reversedMeaning: '不满、贪婪、缺乏满足感',
    keywords: ['satisfaction', 'wishes fulfilled', 'contentment', 'gratification'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Nine_of_Cups_Satisfaction.png',
    suit: 'Cups',
    number: 9,
  },
  {
    id: 45,
    name: '圣杯十',
    nameEn: 'Ten of Cups',
    nameJa: 'カップの10',
    meaning: '家庭和谐、幸福、满足、感情满足',
    reversedMeaning: '家庭破裂、不和谐、不满意',
    keywords: ['family harmony', 'happiness', 'fulfillment', 'emotional satisfaction'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ten_of_Cups_Happiness.png',
    suit: 'Cups',
    number: 10,
  },
  {
    id: 46,
    name: '圣杯侍从',
    nameEn: 'Page of Cups',
    nameJa: 'カップのペイジ',
    meaning: '创造力、直觉、情感消息',
    reversedMeaning: '情感不成熟、创造力受阻',
    keywords: ['creativity', 'intuition', 'emotional messages'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Page_of_Cups_Sensitivity.png',
    suit: 'Cups',
    number: 11,
  },
  {
    id: 47,
    name: '圣杯骑士',
    nameEn: 'Knight of Cups',
    nameJa: 'カップのナイト',
    meaning: '浪漫、魅力、想象力、美',
    reversedMeaning: '情绪化、不可靠、幻想',
    keywords: ['romance', 'charm', 'imagination', 'beauty'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Knight_of_Cups_Romance.png',
    suit: 'Cups',
    number: 12,
  },
  {
    id: 48,
    name: '圣杯王后',
    nameEn: 'Queen of Cups',
    nameJa: 'カップのクイーン',
    meaning: '情感智慧、直觉、同情心、养育',
    reversedMeaning: '情绪化、不安全感、缺乏同情心',
    keywords: ['emotional intelligence', 'intuition', 'compassion', 'nurturing'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Queen_of_Cups_Intuition.png',
    suit: 'Cups',
    number: 13,
  },
  {
    id: 49,
    name: '圣杯国王',
    nameEn: 'King of Cups',
    nameJa: 'カップのキング',
    meaning: '情感平衡、同情心、智慧、冷静',
    reversedMeaning: '情感不稳定、傲慢、控制欲强',
    keywords: ['emotional balance', 'compassion', 'wisdom', 'calmness'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/King_of_Cups_Emotional_maturity.png',
    suit: 'Cups',
    number: 14,
  },
];

// 小阿卡纳 - 宝剑 (Swords) - 14张
export const swordsCards: TarotCardData[] = [
  {
    id: 50,
    name: '宝剑王牌',
    nameEn: 'Ace of Swords',
    nameJa: 'ソードのエース',
    meaning: '突破、清晰、新思想、精神力量',
    reversedMeaning: '困惑、思想混乱、缺乏清晰',
    keywords: ['breakthrough', 'clarity', 'new ideas', 'mental power'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ace_of_Swords_Clarity.png',
    suit: 'Swords',
    number: 1,
  },
  {
    id: 51,
    name: '宝剑二',
    nameEn: 'Two of Swords',
    nameJa: 'ソードの2',
    meaning: '犹豫、难以选择、僵局、避免冲突',
    reversedMeaning: '做出选择、冲突、不确定性',
    keywords: ['hesitation', 'difficult choices', 'deadlock', 'avoiding conflict'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Two_of_Swords_Indecision.png',
    suit: 'Swords',
    number: 2,
  },
  {
    id: 52,
    name: '宝剑三',
    nameEn: 'Three of Swords',
    nameJa: 'ソードの3',
    meaning: '心碎、悲伤、痛苦、情感创伤',
    reversedMeaning: '从痛苦中恢复、释放悲伤、继续前行',
    keywords: ['heartbreak', 'sorrow', 'pain', 'emotional trauma'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Three_of_Swords_Heartbreak.png',
    suit: 'Swords',
    number: 3,
  },
  {
    id: 53,
    name: '宝剑四',
    nameEn: 'Four of Swords',
    nameJa: 'ソードの4',
    meaning: '休息、恢复、沉思、安静',
    reversedMeaning: '焦虑、缺乏休息、恢复受阻',
    keywords: ['rest', 'recovery', 'contemplation', 'quiet'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Four_of_Swords_Rest.png',
    suit: 'Swords',
    number: 4,
  },
  {
    id: 54,
    name: '宝剑五',
    nameEn: 'Five of Swords',
    nameJa: 'ソードの5',
    meaning: '冲突、失败、放弃、背叛',
    reversedMeaning: '避免冲突、寻求解决、妥协',
    keywords: ['conflict', 'defeat', 'giving up', 'betrayal'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Five_of_Swords_Defeat.png',
    suit: 'Swords',
    number: 5,
  },
  {
    id: 55,
    name: '宝剑六',
    nameEn: 'Six of Swords',
    nameJa: 'ソードの6',
    meaning: '过渡、离开平静、离开不稳定、移动',
    reversedMeaning: '停留在不愉快的情况中、被困住',
    keywords: ['transition', 'leaving the calm', 'leaving the turbulent', 'movement'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Six_of_Swords_Transition.png',
    suit: 'Swords',
    number: 6,
  },
  {
    id: 56,
    name: '宝剑七',
    nameEn: 'Seven of Swords',
    nameJa: 'ソードの7',
    meaning: '欺骗、战术、逃跑、寻求出路',
    reversedMeaning: '诚实、直接面对问题、停止逃避',
    keywords: ['deception', 'tactics', 'running away', 'seeking a way out'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Seven_of_Swords_Deception.png',
    suit: 'Swords',
    number: 7,
  },
  {
    id: 57,
    name: '宝剑八',
    nameEn: 'Eight of Swords',
    nameJa: 'ソードの8',
    meaning: '束缚、限制、自我囚禁、受害者心态',
    reversedMeaning: '释放束缚、新视角、自由',
    keywords: ['bondage', 'restriction', 'self-imprisonment', 'victim mentality'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Eight_of_Swords_Restriction.png',
    suit: 'Swords',
    number: 8,
  },
  {
    id: 58,
    name: '宝剑九',
    nameEn: 'Nine of Swords',
    nameJa: 'ソードの9',
    meaning: '焦虑、担忧、噩梦、恐惧',
    reversedMeaning: '释放恐惧、积极思考、解决问题',
    keywords: ['anxiety', 'worry', 'nightmares', 'fear'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Nine_of_Swords_Anxiety.png',
    suit: 'Swords',
    number: 9,
  },
  {
    id: 59,
    name: '宝剑十',
    nameEn: 'Ten of Swords',
    nameJa: 'ソードの10',
    meaning: '痛苦的结束、背叛、损失、绝望',
    reversedMeaning: '恢复、新生、结束痛苦周期',
    keywords: ['painful endings', 'betrayal', 'loss', 'hopelessness'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ten_of_Swords_Ruin.png',
    suit: 'Swords',
    number: 10,
  },
  {
    id: 60,
    name: '宝剑侍从',
    nameEn: 'Page of Swords',
    nameJa: 'ソードのペイジ',
    meaning: '好奇心、新思想、沟通、监控',
    reversedMeaning: '缺乏好奇心、信息不准确、恶意八卦',
    keywords: ['curiosity', 'new ideas', 'communication', 'surveillance'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Page_of_Swords_Curiosity.png',
    suit: 'Swords',
    number: 11,
  },
  {
    id: 61,
    name: '宝剑骑士',
    nameEn: 'Knight of Swords',
    nameJa: 'ソードのナイト',
    meaning: '行动、雄心、追求、快速移动',
    reversedMeaning: '缺乏方向、冲动、攻击性',
    keywords: ['action', 'ambition', 'pursuit', 'rapid movement'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Knight_of_Swords_Impulsiveness.png',
    suit: 'Swords',
    number: 12,
  },
  {
    id: 62,
    name: '宝剑王后',
    nameEn: 'Queen of Swords',
    nameJa: 'ソードのクイーン',
    meaning: '独立、清晰、直接、纪律',
    reversedMeaning: '严厉、孤立、缺乏同情心、冷酷',
    keywords: ['independence', 'clarity', 'directness', 'discipline'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Queen_of_Swords_Independence.png',
    suit: 'Swords',
    number: 13,
  },
  {
    id: 63,
    name: '宝剑国王',
    nameEn: 'King of Swords',
    nameJa: 'ソードのキング',
    meaning: '智力、权威、逻辑、真理',
    reversedMeaning: '操纵、残酷、缺乏同情心、傲慢',
    keywords: ['intellect', 'authority', 'logic', 'truth'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/King_of_Swords_Logic.png',
    suit: 'Swords',
    number: 14,
  },
];

// 小阿卡纳 - 星币 (Pentacles) - 14张
export const pentaclesCards: TarotCardData[] = [
  {
    id: 64,
    name: '星币王牌',
    nameEn: 'Ace of Pentacles',
    nameJa: 'ペンタクルのエース',
    meaning: '新的机会、繁荣、富足、物质成功',
    reversedMeaning: '错失机会、缺乏繁荣、贫穷',
    keywords: ['new opportunities', 'prosperity', 'abundance', 'material success'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ace_of_Pentacles_Material_opportunity.png',
    suit: 'Pentacles',
    number: 1,
  },
  {
    id: 65,
    name: '星币二',
    nameEn: 'Two of Pentacles',
    nameJa: 'ペンタクルの2',
    meaning: '平衡、适应、时间管理、优先事项',
    reversedMeaning: '失衡、缺乏灵活性、不知所措',
    keywords: ['balance', 'adaptability', 'time management', 'priorities'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Two_of_Pentacles_Balance.png',
    suit: 'Pentacles',
    number: 2,
  },
  {
    id: 66,
    name: '星币三',
    nameEn: 'Three of Pentacles',
    nameJa: 'ペンタクルの3',
    meaning: '团队合作、合作、实现目标、技能',
    reversedMeaning: '缺乏团队合作、项目失败、技能不足',
    keywords: ['teamwork', 'collaboration', 'achieving goals', 'skills'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Three_of_Pentacles_Teamwork.png',
    suit: 'Pentacles',
    number: 3,
  },
  {
    id: 67,
    name: '星币四',
    nameEn: 'Four of Pentacles',
    nameJa: 'ペンタクルの4',
    meaning: '贪婪、占有欲、控制、保守',
    reversedMeaning: '慷慨、分享、放开',
    keywords: ['greed', 'possessiveness', 'control', 'conservatism'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Four_of_Pentacles_Security.png',
    suit: 'Pentacles',
    number: 4,
  },
  {
    id: 68,
    name: '星币五',
    nameEn: 'Five of Pentacles',
    nameJa: 'ペンタクルの5',
    meaning: '贫困、缺乏、困难、疾病',
    reversedMeaning: '恢复、改善、帮助可用',
    keywords: ['poverty', 'lack', 'hardship', 'illness'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Five_of_Pentacles_Hardship.png',
    suit: 'Pentacles',
    number: 5,
  },
  {
    id: 69,
    name: '星币六',
    nameEn: 'Six of Pentacles',
    nameJa: 'ペンタクルの6',
    meaning: '慷慨、慈善、分享财富、帮助他人',
    reversedMeaning: '自私、不平等、缺乏帮助',
    keywords: ['generosity', 'charity', 'sharing wealth', 'helping others'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Six_of_Pentacles_Generosity.png',
    suit: 'Pentacles',
    number: 6,
  },
  {
    id: 70,
    name: '星币七',
    nameEn: 'Seven of Pentacles',
    nameJa: 'ペンタクルの7',
    meaning: '耐心、投资、长期目标、等待',
    reversedMeaning: '不耐烦、缺乏投资、短期思考',
    keywords: ['patience', 'investment', 'long-term goals', 'waiting'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Seven_of_Pentacles_Assessment.png',
    suit: 'Pentacles',
    number: 7,
  },
  {
    id: 71,
    name: '星币八',
    nameEn: 'Eight of Pentacles',
    nameJa: 'ペンタクルの8',
    meaning: '技能、勤奋、工匠精神、精通',
    reversedMeaning: '缺乏技能、懒惰、缺乏努力',
    keywords: ['skill', 'diligence', 'craftsmanship', 'mastery'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Eight_of_Pentacles_Dedication.png',
    suit: 'Pentacles',
    number: 8,
  },
  {
    id: 72,
    name: '星币九',
    nameEn: 'Nine of Pentacles',
    nameJa: 'ペンタクルの9',
    meaning: '奢侈品、自给自足、财务独立、成功',
    reversedMeaning: '缺乏奢侈、依赖他人、不成功',
    keywords: ['luxury', 'self-sufficiency', 'financial independence', 'success'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Nine_of_Pentacles_Independence.png',
    suit: 'Pentacles',
    number: 9,
  },
  {
    id: 73,
    name: '星币十',
    nameEn: 'Ten of Pentacles',
    nameJa: 'ペンタクルの10',
    meaning: '财富、家庭遗产、稳定、长期成功',
    reversedMeaning: '财富损失、家庭遗产破裂、不稳定',
    keywords: ['wealth', 'family legacy', 'stability', 'long-term success'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Ten_of_Pentacles_Wealth.png',
    suit: 'Pentacles',
    number: 10,
  },
  {
    id: 74,
    name: '星币侍从',
    nameEn: 'Page of Pentacles',
    nameJa: 'ペンタクルのペイジ',
    meaning: '学习、实践、研究、新商业想法',
    reversedMeaning: '缺乏学习、理论化、不切实际',
    keywords: ['learning', 'practicality', 'study', 'new business ideas'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Page_of_Pentacles_Learning.png',
    suit: 'Pentacles',
    number: 11,
  },
  {
    id: 75,
    name: '星币骑士',
    nameEn: 'Knight of Pentacles',
    nameJa: 'ペンタクルのナイト',
    meaning: '勤奋、可靠、务实、常规',
    reversedMeaning: '懒惰、不切实际、过于常规',
    keywords: ['diligence', 'reliability', 'practicality', 'routine'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Knight_of_Pentacles_Responsibility.png',
    suit: 'Pentacles',
    number: 12,
  },
  {
    id: 76,
    name: '星币王后',
    nameEn: 'Queen of Pentacles',
    nameJa: 'ペンタクルのクイーン',
    meaning: '养育、实用、财务智慧、慷慨',
    reversedMeaning: '不切实际、缺乏财务智慧、自私',
    keywords: ['nurturing', 'practicality', 'financial wisdom', 'generosity'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/Queen_of_Pentacles_Abundance.png',
    suit: 'Pentacles',
    number: 13,
  },
  {
    id: 77,
    name: '星币国王',
    nameEn: 'King of Pentacles',
    nameJa: 'ペンタクルのキング',
    meaning: '财富、商业、领导力、稳定',
    reversedMeaning: '贪婪、物质主义、自私',
    keywords: ['wealth', 'business', 'leadership', 'stability'],
    imageUrl: 'https://raw.githubusercontent.com/ricarvy/tarot_source/main/result/Minor/King_of_Pentacles_Wealth.png',
    suit: 'Pentacles',
    number: 14,
  },
];

// 完整的78张牌
export const allTarotCards: TarotCardData[] = [
  ...majorArcana,
  ...wandsCards,
  ...cupsCards,
  ...swordsCards,
  ...pentaclesCards,
];

// 按ID获取牌
export function getCardById(id: number): TarotCardData | undefined {
  return allTarotCards.find(card => card.id === id);
}

// 获取随机牌（用于抽牌）
export function drawRandomCards(count: number, includeReversed: boolean = true): Array<TarotCardData & { isReversed: boolean }> {
  const shuffled = [...allTarotCards].sort(() => Math.random() - 0.5);
  const drawn = shuffled.slice(0, count);

  return drawn.map(card => ({
    ...card,
    isReversed: includeReversed ? Math.random() > 0.5 : false,
  }));
}

// 按花色获取牌
export function getCardsBySuit(suit: 'Wands' | 'Cups' | 'Swords' | 'Pentacles'): TarotCardData[] {
  return allTarotCards.filter(card => card.suit === suit);
}

// 获取大阿卡纳
export function getMajorArcana(): TarotCardData[] {
  return majorArcana;
}

// 获取小阿卡纳
export function getMinorArcana(): TarotCardData[] {
  return [...wandsCards, ...cupsCards, ...swordsCards, ...pentaclesCards];
}
